### ISSUE TITLE
qiming-backend ns not created

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#114]
migcluster was not created, qiming-backend ns was not created.

```
root@i-k70jhesn:~# kubectl -n backup-tenant-397342740272179860 get clusters.ys.jibudata.com
NAME                 AGE
397976073163303585   14h
root@i-k70jhesn:~# kubectl -n backup-tenant-397342740272179860 get clusters.ys.jibudata.com  397976073163303585 -o json | jq '.status'
null
root@i-k70jhesn:~# kubectl -n backup-tenant-397342740272179860 get migclusters.migration.yinhestor.com
No resources found in backup-tenant-397342740272179860 namespace.
```

**Comment by stoneshi-yunify** [comment]
save the kubeconfig in clusters.ys.jibudata.com/spec and try, it works well.

```
root@i-k70jhesn:~# kubectl --kubeconfig=/tmp/wx.yaml get node
NAME    STATUS   ROLES                  AGE   VERSION
node1   Ready    control-plane,master   42h   v1.21.5
node2   Ready    worker                 42h   v1.21.5
node3   Ready    worker                 42h   v1.21.5
```

**Comment by jerry-jibu** [comment]
After setting the `maxTenantWorker` from 4 to 12, the new tenants are in service.

```
  ...
  expectedTenantWorkers: 5
  inServiceTenantWorkers:
  - backup-worker-5
  - backup-worker-6
  occupiedTenantWorkers:
  - backup-worker-4
  - backup-worker-1
  - backup-worker-2
  - backup-worker-3
  phase: Ready
  state: InService
```
