### ISSUE TITLE
need cluster notready detailed reason

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#36]
```
kubectl -n backup-tenant-375163393243381927 get clusters.ys.jibudata.com 375304733151232167 -o yaml
status:
  conditions:
  - lastHeartbeatTime: "2021-11-02T05:41:46Z"
    lastTransitionTime: "2021-10-03T02:37:51Z"
    message: completed to reconcile cluster
    reason: ReconcileCompleted
    status: "True"
    type: ReconcileComplete
  - lastHeartbeatTime: "2021-11-02T05:41:46Z"
    lastTransitionTime: "2021-10-03T02:37:51Z"
    message: completed to reconcile cluster
    reason: ReconcileCompleted
    status: "False"
    type: ReconcileProgressing
  - lastHeartbeatTime: "2021-11-02T05:41:46Z"
    lastTransitionTime: "2021-11-01T10:59:48Z"
    message: an error on the server ("") has prevented the request from succeeding
    reason: ClusterInitFailure
    status: "False"
    type: ClusterInitialized
  - lastHeartbeatTime: "2021-11-02T05:41:46Z"
    lastTransitionTime: "2021-11-01T10:59:48Z"
    message: cluster isn't ready in backend
    reason: ClusterNotReady
    status: "False"
    type: ClusterAvailable
  phase: NotReady
```

in this case, the cluster is not ready because the server ip in kubeconfig is not valid any more.

A cluster can become notready for many reasons, e.g. uninitialized, invalid kubeconfig, etc.  User needs such information to know why he can not use this cluster to take backup/restore.

Can jibu put more details reason in cluster.status for notready? Then ks can display the reason in console and user will have more clues.
