### ISSUE TITLE
some restore jobs are missing status.report.totalItems

### ISSUE THREAD

**Issue by fuchunlan** [jibutech/backup-saas-client#67]
The restore job is complete  with `status.report.details` but no `status.report.totalItems`
![image](https://user-images.githubusercontent.com/63338728/144537655-41c8b982-868f-42af-a4e9-419416a60d61.png)

**Comment by shaofeng66** [comment]
kubectl -n backup-tenant-1 get restorejobs.migration.yinhestor.com test-3u4vu -o yaml
```
status:
  conditions:
  - category: Warn
    durable: true
    lastTransitionTime: "2021-12-03T02:48:58Z"
    message: 'Restore: qiming-backend/test-3u4vu-nf4qr has 1 warnings'
    reason: RestoreWarning
    status: "True"
    type: FinalRestoreCreated
  - category: Advisory
    durable: true
    lastTransitionTime: "2021-12-03T02:49:16Z"
    message: The job has completed successfully.
    reason: Completed
    status: "True"
    type: Succeeded
  itinerary: Restore
  observedDigest: 4518e8adf1b901520c2932e4180f5b348ca4707aa46273a7f72ef3bd43378d16
  phase: Completed
  results:
    errors: {}
    warnings:
      namespaces:
        ambassador-acl00:
        - 'could not restore, configmaps "kube-root-ca.crt" already exists. Warning:
          the in-cluster version is different than the backed-up version.'
  startTimestamp: "2021-12-03T02:48:10Z"
```

kubectl --kubeconfig 384059335866586514.kubeconfig -n qiming-backend get restores.velero.io test-3u4vu-nf4qr -o yaml
```
status:
  completionTimestamp: "2021-12-03T02:48:57Z"
  phase: Completed
  progress:
    itemsRestored: 34
    totalItems: 34
  startTimestamp: "2021-12-03T02:48:47Z"
  warnings: 1
```
