### ISSUE TITLE
cluster not ready due to snapshot crds not installed

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#82]
```
kubectl -n backup-tenant-369641743475338021 get migclusters.migration.yinhestor.com 386220762958140814 -o yaml
...
spec:
  insecure: true
  isHostCluster: false
  location:
    isOnPublicCloud: false
    provider: ""
  serviceAccountSecretRef:
    name: 386220762958140814-token
    namespace: backup-tenant-369641743475338021
  url: https://139.198.15.193:36443
status:
  conditions:
  - category: Critical
    lastTransitionTime: "2021-12-17T09:58:36Z"
    message: 'Reconcile failed: [error listing volumesnapshot classes: the server
      could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)].
      See controller logs for details.'
    status: "True"
    type: ReconcileFailed
  isInService: true
```

the cluster is notready, and the backup components was not installed in qiming-backend ns.

cluster is totally legal to not install snapshot crds, so this can not be the reason to put it notready.
