### ISSUE TITLE
endtime presents even job not start

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#9]
here is a restore job:
```
status:
  conditions:
  - lastHeartbeatTime: "2021-09-17T04:38:03Z"
    lastTransitionTime: "2021-09-17T04:35:19Z"
    message: reconciling done
    reason: ReconcileCompleted
    status: "True"
    type: ReconcileComplete
  - lastHeartbeatTime: "2021-09-17T04:38:03Z"
    lastTransitionTime: "2021-09-17T04:35:19Z"
    message: reconciling done
    reason: ReconcileCompleted
    status: "False"
    type: ReconcileProgressing
  phase: NotReady
  report:
    endTime: "2021-09-17T04:38:03Z"
```

its phase is notready, but it has a valid endTime.

please check and make sure:
- starttime only presents if job has started, and should never change
- endtime only presents if job has completed or failed, and should never change
- expiredtime only presents if job has started (or has completed?)
